/**
 * Shared mock-auth helpers for the e2e suite.
 *
 * The token embeds a per-run random secret generated by playwright.config.ts
 * (and mirrored into the app server's env). The app only accepts the EXACT
 * `mock-<secret>` value while running under the harness — hardcoded tokens
 * from older specs would no longer authenticate.
 */
export const MOCK_ADMIN_TOKEN = `mock-${process.env.E2E_MOCK_SECRET ?? ''}`;

export interface MockCookie {
  name: string;
  value: string;
  domain: string;
  path: string;
}

export const ADMIN_COOKIE: MockCookie = {
  name: 'betrix_admin_token',
  value: MOCK_ADMIN_TOKEN,
  domain: '127.0.0.1',
  path: '/'
};
