-- D1 Phase 0 — Better Auth initial schema (forward-looking DDL reference)
--
-- This file is a DOCUMENTATION reference for the SQL that Drizzle will emit at
-- `pnpm drizzle-kit generate` time (run in Phase 1, not Phase 0). Phase 0
-- only adds the schema definitions in TS (`packages/infra/src/auth/schemas.ts`)
-- so the BA Drizzle adapter wiring compiles end-to-end. The actual migration
-- is generated by Drizzle from the schema file.
--
-- See: docs/D1-better-auth-migration-plan.md §4.1 (schema diff) and §4.2
-- (data migration risk + sequencing).

CREATE SCHEMA IF NOT EXISTS auth;

-- BA 4 core tables. Column names match BA's API contract; PKs are uuid to
-- stay FK-compatible with identity.users.id and money.* references.

CREATE TABLE IF NOT EXISTS auth."user" (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name          text NOT NULL,
  email         text NOT NULL UNIQUE,
  email_verified boolean NOT NULL DEFAULT false,
  image         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth.session (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  expires_at   timestamptz NOT NULL,
  token        text NOT NULL UNIQUE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  ip_address   text,
  user_agent   text,
  user_id      uuid NOT NULL REFERENCES auth."user"(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS session_user_id_idx ON auth.session (user_id);
CREATE INDEX IF NOT EXISTS session_expires_at_idx ON auth.session (expires_at);

CREATE TABLE IF NOT EXISTS auth.account (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id                text NOT NULL,
  provider_id               text NOT NULL,
  user_id                   uuid NOT NULL REFERENCES auth."user"(id) ON DELETE CASCADE,
  access_token              text,
  refresh_token             text,
  id_token                  text,
  access_token_expires_at   timestamptz,
  refresh_token_expires_at  timestamptz,
  scope                     text,
  password                  text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS account_user_id_idx ON auth.account (user_id);
CREATE INDEX IF NOT EXISTS account_provider_account_idx ON auth.account (provider_id, account_id);

CREATE TABLE IF NOT EXISTS auth.verification (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  identifier  text NOT NULL,
  value       text NOT NULL,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON auth.verification (identifier);
CREATE INDEX IF NOT EXISTS verification_expires_at_idx ON auth.verification (expires_at);

-- Phase 1 will run this exact DDL via `pnpm drizzle-kit generate` +
-- `pnpm drizzle-kit migrate`. The TS schema in
-- `packages/infra/src/auth/schemas.ts` is the single source of truth;
-- this file is for the DBA / reviewer.
--
-- Phase 2 cutover also requires ALTER TABLE identity.users ADD COLUMN
-- updated_at timestamptz NOT NULL DEFAULT now();
-- ALTER TABLE identity.users ADD COLUMN image text;
-- ALTER TABLE identity.sessions ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
-- plus a backfill INSERT into auth.account (password=identity.users.password_hash,
-- provider_id='credential', account_id=identity.users.id or .email).
-- Those ALTERs are documented in §4.1 of the D1 plan and applied in Phase 2.
