-- D1 Phase 0 + Phase 1 — Better Auth initial schema + ALTERs (forward-looking
-- DDL reference)
--
-- This file is a DOCUMENTATION reference for the SQL that Drizzle will emit at
-- `pnpm drizzle-kit generate` time. Phase 0 added the schema definitions in
-- TS (`packages/infra/src/auth/schemas.ts`); Phase 1 also extends
-- `identity.users` and `identity.sessions` with the columns BA needs. The
-- actual migration is generated by Drizzle from the schema files.
--
-- See: docs/D1-better-auth-migration-plan.md §4.1 (schema diff), §4.2 (data
-- migration risk), §4.3 (zero-downtime sequencing).

-- ── Phase 0: new auth schema + 4 BA tables ───────────────────────────────

CREATE SCHEMA IF NOT EXISTS auth;

-- BA 4 core tables. Column names match BA's API contract; PKs are uuid to
-- stay FK-compatible with identity.users.id and money.* references.

CREATE TABLE IF NOT EXISTS auth."user" (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name          text NOT NULL,
  email         text NOT NULL UNIQUE,
  email_verified boolean NOT NULL DEFAULT false,
  image         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth.session (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  expires_at   timestamptz NOT NULL,
  token        text NOT NULL UNIQUE,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  ip_address   text,
  user_agent   text,
  user_id      uuid NOT NULL REFERENCES auth."user"(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS session_user_id_idx ON auth.session (user_id);
CREATE INDEX IF NOT EXISTS session_expires_at_idx ON auth.session (expires_at);

CREATE TABLE IF NOT EXISTS auth.account (
  id                        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id                text NOT NULL,
  provider_id               text NOT NULL,
  user_id                   uuid NOT NULL REFERENCES auth."user"(id) ON DELETE CASCADE,
  access_token              text,
  refresh_token             text,
  id_token                  text,
  access_token_expires_at   timestamptz,
  refresh_token_expires_at  timestamptz,
  scope                     text,
  password                  text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS account_user_id_idx ON auth.account (user_id);
CREATE INDEX IF NOT EXISTS account_provider_account_idx ON auth.account (provider_id, account_id);

CREATE TABLE IF NOT EXISTS auth.verification (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  identifier  text NOT NULL,
  value       text NOT NULL,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS verification_identifier_idx ON auth.verification (identifier);
CREATE INDEX IF NOT EXISTS verification_expires_at_idx ON auth.verification (expires_at);

-- ── Phase 1: ALTER identity.users + identity.sessions ───────────────────
-- BA's adapter reads/writes the `user` and `session` table shape. To keep
-- the legacy `identity.users` / `identity.sessions` tables compatible with
-- BA's expected column set, we extend them in place rather than copying
-- data over. After Phase 2 cutover, BA's Drizzle adapter will read from
-- the `auth."user"` table (per its configured schema), and the legacy
-- `identity.users` rows will be migrated via the backfill script.

ALTER TABLE identity.users
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE identity.users
  ADD COLUMN IF NOT EXISTS image text;

ALTER TABLE identity.sessions
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

-- ── Phase 1: backfill auth.account (run AFTER the schema migrations) ─────
-- Idempotent INSERT: only inserts rows for users with a password_hash that
-- don't already have an auth.account row. Same SQL is what
-- `pnpm --filter @betrix/infra db:backfill:d1` runs (see
-- packages/infra/src/persistence/drizzle/d1-backfill-accounts.ts).

INSERT INTO auth.account (
  id,
  account_id,
  provider_id,
  user_id,
  password,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  u.email,
  'credential',
  u.id,
  u.password_hash,
  now(),
  now()
FROM identity.users AS u
WHERE u.password_hash IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM auth.account AS a
    WHERE a.user_id = u.id
      AND a.provider_id = 'credential'
  );

-- ── Phase 2 (FUTURE, DO NOT RUN YET) ────────────────────────────────────
-- After cutover, legacy `identity.sessions` rows are invalidated:
--   DELETE FROM identity.sessions;
-- And after soak, the legacy `identity.users.password_hash` column is dropped:
--   ALTER TABLE identity.users DROP COLUMN password_hash;
-- Those ALTERs are documented in §4.3 of the D1 plan and applied in
-- Phase 2 / Phase 4 respectively.

